server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cartdb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: cart-service

